Cloud-init integration

diff --git a/scripts/qvm-run b/scripts/qvm-run
--- a/scripts/qvm-run
+++ b/scripts/qvm-run
@@ -3,9 +3,9 @@ set -eu
 
 help_msg="
 Run a VM from a disk in QVM_DIR/machines.
-Optionally enable cloud-init served over HTTP at CLOUD_INIT_ADDR.
+Optionally enable cloud-init, with seed in QVM_DIR/cloud-init.
 
-Usage: $(basename "$0") [-n] [-u] [-d] [-i CLOUD_INIT_ADDR] VM_NAME
+Usage: $(basename "$0") [-n] [-u] [-d] [-b] [-i] VM_NAME
 "
 
 : "${QVM_DIR:-$(pwd)}"
@@ -13,12 +13,12 @@ declare -r QVM_DIR
 declare -r MACHINES_DIR="${QVM_DIR}/machines"
 declare -r RUNTIME_DIR="${QVM_DIR}/run"
 
-declare dry_run cloud_init_addr detach
-
+cloud_init=0
 dry_run=0
 detach=0
 user_net=0
-while getopts hndui: opt; do
+first_boot=0
+while getopts hnduib opt; do
   case "${opt}" in
     n)
       dry_run=1 ;;
@@ -26,11 +26,13 @@ while getopts hndui: opt; do
       echo "${help_msg}"
       exit ;;
     i)
-      cloud_init_addr="${OPTARG}" ;;
+      cloud_init=1 ;;
     d)
       detach=1 ;;
     u)
       user_net=1 ;;
+    b)
+      first_boot=1 ;;
     *)
       exit 1 ;;
   esac
@@ -63,16 +65,26 @@ declare -a args=(
   -cpu host
   -smp 4
   -m 8G
-  -drive "file=${drive},if=virtio"
+  -drive "file=${drive},format=qcow2,if=virtio"
   -drive "if=pflash,format=raw,readonly=on,file=/usr/share/edk2/ovmf/OVMF_CODE.fd"
   # TODO: Make this more flexible
   -cdrom "${QVM_DIR}/iso/rhel-10.0-x86_64-dvd.iso"
 )
 
 # Boot options
-if [[ -n "${cloud_init_addr:-}" ]]; then
-  echo "INFO: Running with cloud-init served at http://${cloud_init_addr}"
-  args+=(-smbios "type=1,serial=ds=nocloud;s=http://${cloud_init_addr}")
+# Give us some time to choose boot device
+if ((first_boot)); then
+  args+=(-boot menu=on,splash-time=5000)
+fi
+
+if ((cloud_init)); then
+  seed="${QVM_DIR}/localds/${vm}.img"
+  if [[ -e "${seed}" ]]; then
+    args+=(-drive "file=${seed},if=virtio,format=raw")
+  else
+    echo "ERROR: Invalid datasource: ${seed}"
+    exit 1
+  fi
 fi
 
 # Networking
@@ -93,7 +105,9 @@ macaddr() {
 }
 
 if ((user_net)); then
-  args+=(-nic "user,model=virtio,hostfwd=tcp::2200-:22")
+  printf -v port "22%02d" $((RANDOM * 100 / 32767 ))
+  echo "INFO: ${vm} SSH port: ${port}"
+  args+=(-nic "user,model=virtio,hostfwd=tcp::${port}-:22")
 else
   args+=(-nic "bridge,br=qvm0,model=virtio,mac=$(macaddr)")
 fi
@@ -104,8 +118,6 @@ if ((detach)); then
       -display none
       -daemonize
       -pidfile "${RUNTIME_DIR}/${vm}".pid
-      # -monitor "telnet::2300,server=on"
-      # -serial "telnet::2301,server=on"
   )
 fi
 
